[package]
name = "alesia-db"
version = "0.1.0"
edition = "2021"


[dependencies]
rusqlite = {version = "0.31.0", features = ["bundled"]}
serde = {version = "1.0.196", features = ["derive"]}
serde_json = "1.0.114"
tokio = { version = "1", features = ["full"] }
